### ISSUE TITLE
Serious issue - needs tending to immedietly

### ISSUE THREAD

**Issue by kacperptak01** [ripytide/audio-network#1]
josh cant code, like he is really fucking bad at it please kick him he will destroy the project

Thanks, Kacper

**Comment by ripytide** [comment]
good point his time here is limited

**Comment by kacperptak01** [comment]
> good point his time here is limited

fantastic idea, leader

**Comment by ripytide** [comment]
oi

**Comment by brmbrmcar** [comment]
why the fuck did you add these people as collaborators
